/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RefresherRouteImport } from './routes/refresher'
import { Route as PrivateHireTestRouteImport } from './routes/private-hire-test'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as PassPlusRouteImport } from './routes/pass-plus'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AreasCoveredRouteImport } from './routes/areas-covered'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RefresherRoute = RefresherRouteImport.update({
  id: '/refresher',
  path: '/refresher',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateHireTestRoute = PrivateHireTestRouteImport.update({
  id: '/private-hire-test',
  path: '/private-hire-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const PassPlusRoute = PassPlusRouteImport.update({
  id: '/pass-plus',
  path: '/pass-plus',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasCoveredRoute = AreasCoveredRouteImport.update({
  id: '/areas-covered',
  path: '/areas-covered',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-covered': typeof AreasCoveredRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/lessons': typeof LessonsRoute
  '/pass-plus': typeof PassPlusRoute
  '/prices': typeof PricesRoute
  '/private-hire-test': typeof PrivateHireTestRoute
  '/refresher': typeof RefresherRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-covered': typeof AreasCoveredRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/lessons': typeof LessonsRoute
  '/pass-plus': typeof PassPlusRoute
  '/prices': typeof PricesRoute
  '/private-hire-test': typeof PrivateHireTestRoute
  '/refresher': typeof RefresherRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/areas-covered': typeof AreasCoveredRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/lessons': typeof LessonsRoute
  '/pass-plus': typeof PassPlusRoute
  '/prices': typeof PricesRoute
  '/private-hire-test': typeof PrivateHireTestRoute
  '/refresher': typeof RefresherRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/areas-covered'
    | '/contact'
    | '/faqs'
    | '/lessons'
    | '/pass-plus'
    | '/prices'
    | '/private-hire-test'
    | '/refresher'
    | '/reviews'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/areas-covered'
    | '/contact'
    | '/faqs'
    | '/lessons'
    | '/pass-plus'
    | '/prices'
    | '/private-hire-test'
    | '/refresher'
    | '/reviews'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/areas-covered'
    | '/contact'
    | '/faqs'
    | '/lessons'
    | '/pass-plus'
    | '/prices'
    | '/private-hire-test'
    | '/refresher'
    | '/reviews'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreasCoveredRoute: typeof AreasCoveredRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  LessonsRoute: typeof LessonsRoute
  PassPlusRoute: typeof PassPlusRoute
  PricesRoute: typeof PricesRoute
  PrivateHireTestRoute: typeof PrivateHireTestRoute
  RefresherRoute: typeof RefresherRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refresher': {
      id: '/refresher'
      path: '/refresher'
      fullPath: '/refresher'
      preLoaderRoute: typeof RefresherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-hire-test': {
      id: '/private-hire-test'
      path: '/private-hire-test'
      fullPath: '/private-hire-test'
      preLoaderRoute: typeof PrivateHireTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass-plus': {
      id: '/pass-plus'
      path: '/pass-plus'
      fullPath: '/pass-plus'
      preLoaderRoute: typeof PassPlusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-covered': {
      id: '/areas-covered'
      path: '/areas-covered'
      fullPath: '/areas-covered'
      preLoaderRoute: typeof AreasCoveredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreasCoveredRoute: AreasCoveredRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  LessonsRoute: LessonsRoute,
  PassPlusRoute: PassPlusRoute,
  PricesRoute: PricesRoute,
  PrivateHireTestRoute: PrivateHireTestRoute,
  RefresherRoute: RefresherRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
